/* =========================================================================
   MY HEALTH — product.js
   -------------------------------------------------------------------------
   ⚠️⚠️ EI FILE EDIT KORLE LIVE SITE-E KONO PORIBORTON HOBE NA! ⚠️⚠️

   Keno? Karon Firebase-e already asol product data ase (admin panel diye
   deoa). app.js-er bootProducts() rule ei rokom:
     • Firebase-e product thakle  -> SHOB SHOMOY Firebase-er data e dekhabe,
                                      ei file-er data completely ignore hoy.
     • Firebase khali thakle only -> tokhoni ei file-er PRODUCTS shomoy
                                      seed hisebe use hoy (notun/fresh site).

   Tahole ei file-ta ki kaje lage?
     1) Offline fallback  — Firebase load na hole site khali na dekhiye
        ei seed data dekhabe.
     2) Notun category-r demo product-er utsho — admin panel > Settings >
        Data > "নতুন ক্যাটাগরির demo product যোগ করো" button ei file theke
        product porhe Firebase-e push kore.
     3) Format reference — notun product kemon dekhte hobe bojhar jonno.

   >>> PRODUCT ADD / EDIT / DELETE korte সবসময় ADMIN PANEL (admin.html)
       byabohar korun — এই ফাইল সরাসরি এডিট করবেন না।

   Live Firebase data-r sathe MIL rakha up-to-date backup file chaile:
   admin panel > Settings > Data > "Backup product.js" button diye
   বর্তমান আসল ডেটা .txt হিসেবে ডাউনলোড করা যায়।
   ========================================================================= */

const PRODUCTS = [
  { id:1, img:"https://images.pexels.com/photos/13787566/pexels-photo-13787566.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Whey Protein Isolate 2kg — Chocolate", goal:"muscle", timing:"postworkout",
    rating:4.8, reviews:412, oldPrice:5200, price:3400, stock:true, tags:["flash","best"], brand:"NutriPro", size:"2 kg · 66 servings",
    desc:"Fast-absorbing 100% whey isolate with 27g protein per scoop. Low in carbs and sugar — ideal for lean muscle building and post-workout recovery.",
    benefits:["27g protein per serving","Supports muscle recovery & growth","Low carb, low sugar","Mixes easily, no clumps"],
    use:{dose:"1 scoop (30g) with 250ml water/milk", when:"Within 30 min after workout", duration:"Daily"} },

  { id:2, img:"https://images.pexels.com/photos/13787561/pexels-photo-13787561.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Vitamin C 1000mg with Zinc, 60 Tablets", goal:"immunity", timing:"morning",
    rating:4.7, reviews:289, oldPrice:850, price:599, stock:true, tags:["best"], brand:"VitaLife", size:"60 tablets",
    desc:"High-strength Vitamin C with Zinc to support your immune system, skin health and natural defense — especially during seasonal changes.",
    benefits:["Boosts immune defense","Antioxidant support","Zinc for faster recovery","One-a-day dosing"],
    use:{dose:"1 tablet daily", when:"After breakfast", duration:"Ongoing"} },

  { id:3, img:"https://images.pexels.com/photos/13779107/pexels-photo-13779107.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Omega-3 Fish Oil 1000mg, 120 Softgels", goal:"brain", timing:"anytime",
    rating:4.9, reviews:531, oldPrice:1800, price:1290, stock:true, tags:["best","flash"], brand:"OceanPure", size:"120 softgels",
    desc:"Premium fish oil rich in EPA & DHA for heart, brain and joint health. Molecularly distilled for purity, no fishy aftertaste.",
    benefits:["Supports heart & brain","EPA + DHA omega-3","Joint & eye health","Purified, no fishy burp"],
    use:{dose:"1–2 softgels daily", when:"With a meal", duration:"Ongoing"} },

  { id:4, img:"https://images.pexels.com/photos/11361813/pexels-photo-11361813.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Magnesium Glycinate 400mg, 90 Capsules", goal:"sleep", timing:"night",
    rating:4.6, reviews:174, oldPrice:1400, price:990, stock:true, tags:["new"], brand:"CalmWell", size:"90 capsules",
    desc:"Highly absorbable magnesium glycinate to relax muscles, ease stress and promote deeper, more restful sleep.",
    benefits:["Promotes relaxation & sleep","Eases muscle cramps","Gentle on stomach","Supports nervous system"],
    use:{dose:"2 capsules", when:"30–60 min before bed", duration:"Daily"} },

  { id:5, img:"https://images.pexels.com/photos/14433552/pexels-photo-14433552.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"BCAA 2:1:1 Energy Powder — Mango, 30 Serv", goal:"muscle", timing:"postworkout",
    rating:4.5, reviews:98, oldPrice:2200, price:1650, stock:true, tags:["flash"], brand:"NutriPro", size:"300g · 30 servings",
    desc:"Branched-chain amino acids in the ideal 2:1:1 ratio to reduce muscle breakdown, fight fatigue and speed up recovery.",
    benefits:["Reduces muscle fatigue","Faster recovery","Refreshing mango flavor","Sugar-free"],
    use:{dose:"1 scoop with 300ml water", when:"During / after workout", duration:"Training days"} },

  { id:6, img:"https://images.pexels.com/photos/13787566/pexels-photo-13787566.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Vitamin D3 2000 IU, 120 Softgels", goal:"bones", timing:"morning",
    rating:4.8, reviews:362, oldPrice:900, price:650, stock:true, tags:["best"], brand:"VitaLife", size:"120 softgels",
    desc:"Sunshine vitamin for strong bones, immunity and mood. Essential for anyone with limited sun exposure.",
    benefits:["Strengthens bones & teeth","Supports immunity","Improves mood","Aids calcium absorption"],
    use:{dose:"1 softgel daily", when:"With a meal", duration:"Ongoing"} },

  { id:7, img:"https://images.pexels.com/photos/13787561/pexels-photo-13787561.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Ashwagandha KSM-66 600mg, 90 Caps", goal:"sleep", timing:"night",
    rating:4.7, reviews:245, oldPrice:1600, price:1150, stock:true, tags:["best","new"], brand:"HerbRoot", size:"90 capsules",
    desc:"Clinically-studied KSM-66 ashwagandha to lower stress, improve sleep quality and support energy & focus.",
    benefits:["Reduces stress & anxiety","Improves sleep quality","Supports stamina","Adaptogenic herb"],
    use:{dose:"1 capsule", when:"After dinner", duration:"Daily for 8+ weeks"} },

  { id:8, img:"https://images.pexels.com/photos/13779107/pexels-photo-13779107.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Multivitamin for Men, 60 Tablets", goal:"energy", timing:"morning",
    rating:4.6, reviews:201, oldPrice:1200, price:849, stock:true, tags:[], brand:"VitaLife", size:"60 tablets",
    desc:"Complete daily multivitamin with 24 essential vitamins and minerals to fill nutritional gaps and support all-day energy.",
    benefits:["24 vitamins & minerals","All-day energy support","Immunity & metabolism","Convenient one-a-day"],
    use:{dose:"1 tablet daily", when:"After breakfast", duration:"Ongoing"} },

  { id:9, img:"https://images.pexels.com/photos/11361813/pexels-photo-11361813.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Biotin 10000mcg Hair & Skin, 60 Caps", goal:"skin", timing:"anytime",
    rating:4.5, reviews:156, oldPrice:1100, price:799, stock:true, tags:["new"], brand:"GlowLab", size:"60 capsules",
    desc:"High-potency biotin to strengthen hair, support nail growth and promote healthy, glowing skin.",
    benefits:["Stronger hair & nails","Healthy glowing skin","Reduces hair fall","High 10000mcg dose"],
    use:{dose:"1 capsule daily", when:"With a meal", duration:"3+ months for best results"} },

  { id:10, img:"https://images.pexels.com/photos/14433552/pexels-photo-14433552.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Vitamin B-Complex, 100 Tablets", goal:"energy", timing:"morning",
    rating:4.7, reviews:188, oldPrice:700, price:520, stock:true, tags:["flash"], brand:"VitaLife", size:"100 tablets",
    desc:"All 8 B vitamins in one tablet to convert food into energy, support brain function and reduce tiredness.",
    benefits:["Fights fatigue","Supports metabolism","Healthy nervous system","All 8 B-vitamins"],
    use:{dose:"1 tablet daily", when:"After breakfast", duration:"Ongoing"} },

  { id:11, img:"https://images.pexels.com/photos/13787566/pexels-photo-13787566.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Calcium + Magnesium + Zinc, 90 Tabs", goal:"bones", timing:"anytime",
    rating:4.6, reviews:142, oldPrice:950, price:699, stock:true, tags:[], brand:"BoneStrong", size:"90 tablets",
    desc:"Triple-mineral formula for strong bones, muscle function and recovery — perfect for active adults and seniors.",
    benefits:["Strong bones & joints","Muscle function","Better mineral absorption","3-in-1 formula"],
    use:{dose:"1 tablet", when:"After dinner", duration:"Ongoing"} },

  { id:12, img:"https://images.pexels.com/photos/13787561/pexels-photo-13787561.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"L-Carnitine Fat Burner 500mg, 60 Caps", goal:"weight", timing:"morning",
    rating:4.4, reviews:87, oldPrice:1500, price:1099, stock:true, tags:["flash"], brand:"LeanFit", size:"60 capsules",
    desc:"Helps your body turn fat into energy. Great alongside exercise for weight management and workout performance.",
    benefits:["Supports fat metabolism","Boosts workout energy","Stimulant-free","Vegetarian capsule"],
    use:{dose:"1 capsule", when:"30 min before workout", duration:"Training days"} },

  { id:13, img:"https://images.pexels.com/photos/13779107/pexels-photo-13779107.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Creatine Monohydrate 300g Micronized", goal:"muscle", timing:"postworkout",
    rating:4.9, reviews:476, oldPrice:1800, price:1290, stock:true, tags:["best"], brand:"NutriPro", size:"300g · 60 servings",
    desc:"The most researched supplement for strength and power. Micronized for easy mixing — increases muscle volume and performance.",
    benefits:["More strength & power","Increases muscle volume","100% pure creatine","Unflavored, mixes easily"],
    use:{dose:"5g (1 scoop) with water/juice", when:"Post-workout or anytime", duration:"Daily"} },

  { id:14, img:"https://images.pexels.com/photos/14433552/pexels-photo-14433552.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Elderberry + Vitamin C Immune Gummies", goal:"immunity", timing:"anytime",
    rating:4.7, reviews:233, oldPrice:1300, price:950, stock:true, tags:["new"], brand:"VitaLife", size:"60 gummies",
    desc:"Delicious elderberry gummies packed with Vitamin C and Zinc — immune support the whole family will enjoy.",
    benefits:["Tasty immune support","Elderberry + Vit C + Zinc","Great for kids & adults","No artificial colors"],
    use:{dose:"2 gummies daily", when:"Anytime", duration:"Ongoing"} },

  { id:15, img:"https://images.pexels.com/photos/14433552/pexels-photo-14433552.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Green Tea Extract 500mg, 90 Caps", goal:"weight", timing:"morning",
    rating:4.5, reviews:119, oldPrice:850, price:620, stock:true, tags:[], brand:"HerbRoot", size:"90 capsules",
    desc:"Concentrated green tea extract rich in EGCG antioxidants to support metabolism and natural fat burning.",
    benefits:["Supports metabolism","Rich in antioxidants","Natural energy","Supports fat loss"],
    use:{dose:"1 capsule", when:"Before meals", duration:"Daily"} },

  { id:16, img:"https://images.pexels.com/photos/13787566/pexels-photo-13787566.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Collagen Peptides Powder 250g", goal:"skin", timing:"anytime",
    rating:4.8, reviews:301, oldPrice:2400, price:1790, stock:true, tags:["best","flash"], brand:"GlowLab", size:"250g · 25 servings",
    desc:"Hydrolyzed collagen peptides for youthful skin, stronger hair & nails, and healthy joints. Unflavored — mix into anything.",
    benefits:["Smoother, firmer skin","Stronger hair & nails","Joint support","Dissolves clear, tasteless"],
    use:{dose:"1 scoop (10g)", when:"In coffee, water or smoothie", duration:"Daily for 8+ weeks"} },

  { id:17, img:"https://images.pexels.com/photos/13787561/pexels-photo-13787561.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Probiotic 50 Billion CFU, 60 Caps", goal:"immunity", timing:"morning",
    rating:4.6, reviews:167, oldPrice:1900, price:1450, stock:true, tags:["new"], brand:"GutWell", size:"60 capsules",
    desc:"50 billion CFU across 12 strains to balance gut flora, improve digestion and strengthen immunity.",
    benefits:["Better digestion","Gut & immune health","12 probiotic strains","Reduces bloating"],
    use:{dose:"1 capsule daily", when:"Empty stomach, morning", duration:"Ongoing"} },

  { id:18, img:"https://images.pexels.com/photos/13779107/pexels-photo-13779107.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Pre-Workout Energy — Blue Raspberry, 30 Serv", goal:"energy", timing:"postworkout",
    rating:4.7, reviews:214, oldPrice:2500, price:1850, stock:true, tags:["flash"], brand:"NutriPro", size:"300g · 30 servings",
    desc:"Explosive energy, focus and pumps. Caffeine, beta-alanine and citrulline to power through your hardest sessions.",
    benefits:["Intense energy & focus","Better pumps","Delays fatigue","Refreshing flavor"],
    use:{dose:"1 scoop with 300ml water", when:"20 min before workout", duration:"Training days"} },

  { id:19, img:"https://images.pexels.com/photos/11361813/pexels-photo-11361813.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Mass Gainer 3kg — Banana", goal:"muscle", timing:"postworkout",
    rating:4.5, reviews:132, oldPrice:4500, price:3200, stock:true, tags:[], brand:"NutriPro", size:"3 kg",
    desc:"High-calorie gainer with protein and complex carbs to help hard-gainers build size and strength.",
    benefits:["High calories for bulking","Protein + carbs blend","Supports weight gain","Great taste"],
    use:{dose:"2 scoops with 400ml milk", when:"After workout / between meals", duration:"Daily"} },

  { id:20, img:"https://images.pexels.com/photos/14433552/pexels-photo-14433552.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Melatonin 5mg Sleep Aid, 100 Tablets", goal:"sleep", timing:"night",
    rating:4.6, reviews:178, oldPrice:600, price:430, stock:true, tags:["best"], brand:"CalmWell", size:"100 tablets",
    desc:"Helps you fall asleep faster and reset your sleep cycle — perfect for jet lag or irregular schedules.",
    benefits:["Fall asleep faster","Resets sleep cycle","Non-habit forming","Wake refreshed"],
    use:{dose:"1 tablet", when:"30 min before bed", duration:"As needed"} },

  { id:21, img:"https://images.pexels.com/photos/13787566/pexels-photo-13787566.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Lion's Mane Mushroom 1000mg, 60 Caps", goal:"brain", timing:"morning",
    rating:4.7, reviews:96, oldPrice:1700, price:1280, stock:true, tags:["new"], brand:"HerbRoot", size:"60 capsules",
    desc:"Nootropic mushroom traditionally used to support memory, focus and mental clarity.",
    benefits:["Supports memory & focus","Mental clarity","Nervous system support","Natural nootropic"],
    use:{dose:"1 capsule", when:"With breakfast", duration:"Daily"} },

  { id:22, img:"https://images.pexels.com/photos/13787561/pexels-photo-13787561.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Iron + Folic Acid for Women, 60 Tablets", goal:"energy", timing:"morning",
    rating:4.5, reviews:143, oldPrice:550, price:399, stock:true, tags:[], brand:"VitaLife", size:"60 tablets",
    desc:"Gentle iron with folic acid to fight tiredness and support healthy blood — formulated for women's needs.",
    benefits:["Fights fatigue & anemia","Gentle on stomach","With folic acid","Supports energy"],
    use:{dose:"1 tablet daily", when:"After a meal", duration:"As advised"} },
  { id:23, img:"https://images.pexels.com/photos/13779107/pexels-photo-13779107.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Best Naturals TUDCA 250mg, 60 Capsules", goal:"energy", timing:"anytime",
    rating:4.7, reviews:64, oldPrice:4550, price:4050, stock:true, tags:["new"], brand:"Best Naturals", size:"60 capsules",
    desc:"TUDCA (Tauroursodeoxycholic acid) supports healthy liver function, bile flow and cellular detox.",
    benefits:["Supports liver health", "Aids bile flow", "Cellular protection", "60 capsule supply"],
    use:{dose:"1 capsule", when:"With a meal", duration:"Daily"} },
  { id:24, img:"https://images.pexels.com/photos/11361813/pexels-photo-11361813.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Futurebiotics Vitamin K2 + D3, 120 Capsules", goal:"bones", timing:"morning",
    rating:4.8, reviews:88, oldPrice:3650, price:3250, stock:true, tags:["new"], brand:"Futurebiotics", size:"120 capsules",
    desc:"Vitamin K2 with D3 work together for strong bones and proper calcium use in the body.",
    benefits:["Strong bones & teeth", "Supports heart health", "Better calcium absorption", "K2 + D3 combo"],
    use:{dose:"1 capsule", when:"After breakfast", duration:"Ongoing"} },
  { id:25, img:"https://images.pexels.com/photos/14433552/pexels-photo-14433552.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Life Extension Chromium 500mcg, 60 Veg Capsules", goal:"weight", timing:"morning",
    rating:4.6, reviews:52, oldPrice:2250, price:2050, stock:true, tags:["new"], brand:"Life Extension", size:"60 veg capsules",
    desc:"Optimized chromium helps support healthy blood sugar levels and metabolism.",
    benefits:["Supports blood sugar balance", "Aids metabolism", "Reduces cravings", "Vegetarian capsule"],
    use:{dose:"1 capsule", when:"Before a meal", duration:"Daily"} },
  { id:26, img:"https://images.pexels.com/photos/13787566/pexels-photo-13787566.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"NeoCell Super Collagen + Vitamin C & Biotin, 180 Tablets", goal:"skin", timing:"anytime",
    rating:4.8, reviews:214, oldPrice:3450, price:3250, stock:true, tags:["new"], brand:"NeoCell", size:"180 tablets",
    desc:"Collagen with Vitamin C and Biotin for radiant skin, strong hair and healthy nails.",
    benefits:["Glowing, firmer skin", "Stronger hair & nails", "Collagen + C + Biotin", "180 tablet supply"],
    use:{dose:"3 tablets", when:"Anytime", duration:"Daily for 8+ weeks"} },
  { id:27, img:"https://images.pexels.com/photos/13787561/pexels-photo-13787561.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"NOW Foods Omega-3 Fish Oil, 200 Softgels", goal:"brain", timing:"anytime",
    rating:4.9, reviews:331, oldPrice:3850, price:3550, stock:true, tags:["new"], brand:"NOW Foods", size:"200 softgels",
    desc:"High-quality omega-3 fish oil with EPA & DHA for heart, brain and joint health.",
    benefits:["Supports heart & brain", "EPA + DHA", "Joint & eye health", "200 softgel value pack"],
    use:{dose:"2 softgels", when:"With a meal", duration:"Ongoing"} },
  { id:28, img:"https://images.pexels.com/photos/13779107/pexels-photo-13779107.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Swanson Scottish Kelp 750mg, 30 Veggie Capsules", goal:"energy", timing:"morning",
    rating:4.5, reviews:41, oldPrice:2050, price:1850, stock:true, tags:["new"], brand:"Swanson", size:"30 veggie capsules",
    desc:"Natural sea kelp providing iodine to support healthy thyroid function and energy.",
    benefits:["Supports thyroid", "Natural iodine source", "Boosts energy", "Organic sea kelp"],
    use:{dose:"1 capsule", when:"With breakfast", duration:"Daily"} },
  { id:29, img:"https://images.pexels.com/photos/11361813/pexels-photo-11361813.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"NOW Foods Berberine Glucose Support, 90 Softgels", goal:"weight", timing:"morning",
    rating:4.7, reviews:96, oldPrice:5250, price:4850, stock:true, tags:["new"], brand:"NOW Foods", size:"90 softgels",
    desc:"Berberine supports healthy blood sugar, metabolism and cardiovascular wellness.",
    benefits:["Blood sugar support", "Aids metabolism", "Heart wellness", "90 softgels"],
    use:{dose:"1 softgel", when:"Before meals", duration:"Daily"} },
  { id:30, img:"https://images.pexels.com/photos/14433552/pexels-photo-14433552.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Doctor's Best PepZin GI Zinc-L-Carnosine, 120 Veg Capsules", goal:"immunity", timing:"morning",
    rating:4.6, reviews:73, oldPrice:4550, price:4250, stock:true, tags:["new"], brand:"Doctor's Best", size:"120 veg capsules",
    desc:"Zinc-L-Carnosine complex supports stomach lining health, digestion and immunity.",
    benefits:["Supports gut lining", "Aids digestion", "Immune support", "Vegetarian capsule"],
    use:{dose:"1 capsule", when:"Empty stomach", duration:"Daily"} },
  { id:31, img:"https://images.pexels.com/photos/13787566/pexels-photo-13787566.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Life Extension N-Acetyl-L-Cysteine (NAC) 600mg, 60 Caps", goal:"immunity", timing:"anytime",
    rating:4.7, reviews:118, oldPrice:2750, price:2650, stock:true, tags:["new"], brand:"Life Extension", size:"60 capsules",
    desc:"NAC is a powerful antioxidant that supports respiratory health, immunity and detox.",
    benefits:["Antioxidant support", "Respiratory & immune health", "Supports detox", "600mg per cap"],
    use:{dose:"1 capsule", when:"With or without food", duration:"Daily"} },
  { id:32, img:"https://images.pexels.com/photos/13787561/pexels-photo-13787561.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"NOW Foods Glutathione 500mg, 30 Veg Capsules", goal:"skin", timing:"morning",
    rating:4.6, reviews:87, oldPrice:2850, price:2550, stock:true, tags:["new"], brand:"NOW Foods", size:"30 veg capsules",
    desc:"Glutathione, the body's master antioxidant, supports skin brightness and detox.",
    benefits:["Skin brightness", "Master antioxidant", "Supports detox", "Vegetarian capsule"],
    use:{dose:"1 capsule", when:"Empty stomach", duration:"Daily"} },
  { id:33, img:"https://images.pexels.com/photos/13779107/pexels-photo-13779107.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Protocol for Life Balance Magnesium Glycinate, 180 Veg Caps", goal:"sleep", timing:"night",
    rating:4.8, reviews:142, oldPrice:4850, price:4550, stock:true, tags:["new"], brand:"Protocol for Life Balance", size:"180 veg capsules",
    desc:"Highly absorbable magnesium glycinate to relax muscles, ease stress and improve sleep.",
    benefits:["Promotes relaxation & sleep", "Eases muscle cramps", "High absorption", "180 capsule supply"],
    use:{dose:"2 capsules", when:"Before bed", duration:"Daily"} },
  { id:34, img:"https://images.pexels.com/photos/11361813/pexels-photo-11361813.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Nutricost Women Myo & D-Chiro Inositol, 120 Capsules", goal:"energy", timing:"morning",
    rating:4.7, reviews:103, oldPrice:4250, price:3850, stock:true, tags:["new"], brand:"Nutricost", size:"120 capsules",
    desc:"Myo & D-Chiro Inositol in the 40:1 ratio to support women's hormonal balance and energy.",
    benefits:["Supports hormone balance", "Women's wellness", "40:1 inositol ratio", "Boosts energy"],
    use:{dose:"2 capsules", when:"Morning", duration:"Daily"} },

  /* ---------------- 1 demo product per new category ---------------- */
  { id:35, name:"Gentle Foaming Face Cleanser, 150ml", goal:"cleanser", timing:"anytime",
    rating:4.6, reviews:58, oldPrice:950, price:750, stock:true, tags:["new"], brand:"GlowLab", size:"150ml",
    desc:"Sulfate-free foaming cleanser that removes dirt and makeup without stripping the skin's natural moisture.",
    benefits:["Deep cleanses pores", "Sulfate-free formula", "Suitable for daily use", "Non-drying"],
    use:{dose:"Small amount", when:"Morning & night", duration:"Daily"} },

  { id:37, name:"Anti-Hairfall Shampoo, 400ml", goal:"shampoo", timing:"anytime",
    rating:4.5, reviews:134, oldPrice:750, price:590, stock:true, tags:["best"], brand:"HerbRoot", size:"400ml",
    desc:"Strengthening shampoo formulated with biotin and keratin to reduce hair fall and add volume.",
    benefits:["Reduces hair fall", "Strengthens roots", "Adds volume & shine", "Sulfate-free"],
    use:{dose:"Small amount", when:"2-3 times a week", duration:"Ongoing"} },

  { id:39, name:"Shea Butter Body Wash, 500ml", goal:"bodywash", timing:"anytime",
    rating:4.6, reviews:64, oldPrice:650, price:520, stock:true, tags:[], brand:"GlowLab", size:"500ml",
    desc:"Moisturizing body wash with shea butter that cleanses without drying out the skin.",
    benefits:["Deep moisturizing", "Soft, smooth skin", "Gentle fragrance", "Sulfate-free"],
    use:{dose:"Small amount", when:"Daily shower", duration:"Daily"} },

  { id:41, name:"Matte Liquid Foundation, 30ml", goal:"face-makeup", timing:"anytime",
    rating:4.4, reviews:52, oldPrice:1450, price:1150, stock:true, tags:["new"], brand:"GlowLab", size:"30ml",
    desc:"Long-wearing matte foundation with buildable, full coverage for a flawless finish.",
    benefits:["Full coverage", "Matte, long-lasting finish", "Lightweight feel", "Wide shade range"],
    use:{dose:"Few drops", when:"Before events / daily", duration:"As needed"} },

  { id:43, name:"Baby Gentle Wash & Shampoo, 400ml", goal:"babycare", timing:"anytime",
    rating:4.8, reviews:112, oldPrice:750, price:620, stock:true, tags:["best"], brand:"VitaLife", size:"400ml",
    desc:"Tear-free, hypoallergenic wash and shampoo gentle enough for a baby's delicate skin and hair.",
    benefits:["Tear-free formula", "Hypoallergenic", "Dermatologist tested", "Mild, gentle fragrance"],
    use:{dose:"Small amount", when:"Bath time", duration:"Daily"} },

  { id:45, name:"Beard Growth Oil, 30ml", goal:"beardcare", timing:"anytime",
    rating:4.5, reviews:41, oldPrice:650, price:520, stock:true, tags:["new"], brand:"HerbRoot", size:"30ml",
    desc:"Nourishing beard oil that softens facial hair, reduces itchiness and promotes a fuller beard.",
    benefits:["Softens beard hair", "Reduces itchiness", "Promotes growth", "Non-greasy finish"],
    use:{dose:"3-4 drops", when:"Morning & night", duration:"Daily"} },

  { id:47, name:"100% Natural Sundarban Honey, 500g", goal:"honey", timing:"anytime",
    rating:4.9, reviews:167, oldPrice:950, price:790, stock:true, tags:["best"], brand:"NutriPro", size:"500g",
    desc:"Pure, raw honey sourced from the Sundarbans — unprocessed and unheated to preserve natural enzymes.",
    benefits:["100% raw & natural", "No added sugar", "Rich in antioxidants", "Sourced from Sundarbans"],
    use:{dose:"1-2 tsp", when:"Anytime", duration:"Daily"} },

  /* =========================================================================
     BULK CATALOG — 66 products across all categories, added from admin request.
     Brand/product names are real, widely-sold retail products (factual data,
     not copyrightable); descriptions/benefits written fresh, not copied from
     any source. No `img` — uses the branded placeholder until real photos added.
     ========================================================================= */

  /* ---------------- Face Care ---------------- */
  { id:48, name:"Anua Heartleaf 77% Soothing Toner, 250ml", goal:"cleanser", timing:"anytime",
    rating:4.7, reviews:212, oldPrice:2290, price:1890, stock:true, tags:["best"], brand:"Anua", size:"250ml",
    desc:"Heartleaf-based soothing toner that calms irritated skin and preps it for the rest of your routine.",
    benefits:["Calms redness & irritation", "Balances skin pH", "Lightweight, fast-absorbing", "Fragrance-free"],
    use:{dose:"2-3 pumps on cotton pad", when:"Morning & night", duration:"Daily"} },
  { id:49, name:"A'pieu Deep Clean Cleansing Oil, 160ml", goal:"cleanser", timing:"night",
    rating:4.5, reviews:88, oldPrice:1190, price:990, stock:true, tags:["new"], brand:"Apieu", size:"160ml",
    desc:"Oil-based cleanser that melts away makeup and sunscreen without stripping the skin.",
    benefits:["Removes makeup & SPF", "Non-drying formula", "Emulsifies with water", "Suitable for daily use"],
    use:{dose:"1-2 pumps on dry skin", when:"Evening, before face wash", duration:"Daily"} },
  { id:50, name:"ACM Sebionex Cleansing Gel, 200ml", goal:"cleanser", timing:"anytime",
    rating:4.6, reviews:54, oldPrice:1790, price:1490, stock:true, tags:[], brand:"ACM", size:"200ml",
    desc:"Gentle cleansing gel formulated for oily and blemish-prone skin.",
    benefits:["Controls excess oil", "Gentle on sensitive skin", "Soap-free formula", "Dermatologist-developed"],
    use:{dose:"Small amount, lather with water", when:"Morning & night", duration:"Daily"} },
  { id:51, name:"Ambre Solaire SPF 50 Sensitive Nourishing Protection Oil, 150ml", goal:"sunscreen", timing:"morning",
    rating:4.6, reviews:76, oldPrice:1690, price:1390, stock:true, tags:["best"], brand:"Garnier", size:"150ml",
    desc:"High-protection sun oil for sensitive skin that nourishes while shielding from UVA/UVB rays.",
    benefits:["SPF 50 broad protection", "Nourishing, non-greasy", "For sensitive skin", "Water-resistant"],
    use:{dose:"Apply generously", when:"Before sun exposure", duration:"Reapply every 2 hours"} },
  { id:52, name:"Abib Quick Sunstick Protection Bar SPF50+ PA++++, 22g", goal:"sunscreen", timing:"morning",
    rating:4.7, reviews:63, oldPrice:1750, price:1550, stock:true, tags:["new"], brand:"Abib", size:"22g",
    desc:"Convenient stick sunscreen for quick, mess-free reapplication over makeup.",
    benefits:["SPF50+ PA++++", "No white cast", "Easy stick application", "Travel-friendly"],
    use:{dose:"Swipe evenly over face", when:"Morning & reapply midday", duration:"Daily"} },
  { id:53, name:"Anua Airy Sun Cream SPF50+, 50ml", goal:"sunscreen", timing:"morning",
    rating:4.8, reviews:141, oldPrice:1890, price:1690, stock:true, tags:["best"], brand:"Anua", size:"50ml",
    desc:"Lightweight, airy-finish sunscreen that layers well under makeup without pilling.",
    benefits:["SPF50+ protection", "Airy, non-sticky finish", "No white cast", "Makeup-friendly base"],
    use:{dose:"Apply generously to face", when:"Morning, before sun exposure", duration:"Daily"} },
  { id:54, name:"Anua Niacinamide 10% + TXA 4% Serum, 30ml", goal:"serum", timing:"night",
    rating:4.7, reviews:198, oldPrice:2890, price:1790, stock:true, tags:["flash","best"], brand:"Anua", size:"30ml",
    desc:"Brightening serum with niacinamide and TXA to even out tone and fade discoloration.",
    benefits:["Brightens & evens tone", "Fades dark spots", "Reduces oil production", "Lightweight texture"],
    use:{dose:"3-4 drops", when:"Evening, after toner", duration:"Daily"} },
  { id:55, name:"Anua PDRN Hyaluronic Acid Capsule 100 Serum, 30ml", goal:"serum", timing:"night",
    rating:4.8, reviews:104, oldPrice:2490, price:1790, stock:true, tags:["flash"], brand:"Anua", size:"30ml",
    desc:"Hydrating repair serum with PDRN and hyaluronic acid for plumper, more resilient skin.",
    benefits:["Deep hydration", "Supports skin repair", "Plumps fine lines", "Lightweight gel texture"],
    use:{dose:"3-4 drops", when:"Evening, after cleansing", duration:"Daily"} },
  { id:56, name:"3W Clinic Collagen Eye Cream Whitening, 40ml", goal:"moisturizer", timing:"night",
    rating:4.4, reviews:47, oldPrice:790, price:690, stock:true, tags:[], brand:"3W Clinic", size:"40ml",
    desc:"Collagen-infused eye cream that targets dark circles and fine lines around the eyes.",
    benefits:["Brightens under-eye area", "Reduces puffiness", "Firms with collagen", "Gentle, fragrance-light"],
    use:{dose:"Small dot, pat gently", when:"Morning & night", duration:"Daily"} },
  { id:57, name:"APLB Retinol Vitamin C Vitamin E Facial Cream, 55ml", goal:"moisturizer", timing:"night",
    rating:4.6, reviews:71, oldPrice:1390, price:1090, stock:true, tags:["new"], brand:"APLB", size:"55ml",
    desc:"Multi-active night cream combining retinol, vitamin C and vitamin E for renewal and radiance.",
    benefits:["Supports skin renewal", "Brightens complexion", "Antioxidant protection", "Rich, nourishing texture"],
    use:{dose:"Small amount", when:"Evening, last step", duration:"Daily"} },

  /* ---------------- Hair Care ---------------- */
  { id:58, name:"3W Clinic Black Bean Vitalizing Shampoo, 500ml", goal:"shampoo", timing:"anytime",
    rating:4.5, reviews:92, oldPrice:1790, price:1550, stock:true, tags:["best"], brand:"3W Clinic", size:"500ml",
    desc:"Black bean protein shampoo that strengthens hair from root to tip.",
    benefits:["Strengthens hair strands", "Adds natural shine", "Gentle daily formula", "Rich lather"],
    use:{dose:"Small amount, lather & rinse", when:"Every wash", duration:"As needed"} },
  { id:59, name:"Alberto Balsam Blends Damage Repair Shampoo, 300ml", goal:"shampoo", timing:"anytime",
    rating:4.3, reviews:58, oldPrice:550, price:450, stock:true, tags:[], brand:"Alberto Balsam", size:"300ml",
    desc:"Affordable everyday shampoo formulated to repair damaged, over-styled hair.",
    benefits:["Repairs damaged hair", "Affordable everyday use", "Gentle cleansing", "Pleasant fragrance"],
    use:{dose:"Small amount, lather & rinse", when:"Every wash", duration:"As needed"} },
  { id:60, name:"Alpecin Caffeine Shampoo C1 Black Edition, 250ml", goal:"shampoo", timing:"anytime",
    rating:4.6, reviews:133, oldPrice:1990, price:1990, stock:true, tags:["best"], brand:"Alpecin", size:"250ml",
    desc:"Caffeine shampoo designed to energize hair roots and help reduce hereditary hair loss.",
    benefits:["Caffeine root energizer", "Helps reduce hair fall", "For daily use", "Fresh, clean scent"],
    use:{dose:"Massage into scalp, leave 2 min", when:"Every wash", duration:"Daily use recommended"} },
  { id:61, name:"Alpecin Dandruff Killer Shampoo, 250ml", goal:"shampoo", timing:"anytime",
    rating:4.4, reviews:67, oldPrice:1990, price:1990, stock:true, tags:["new"], brand:"Alpecin", size:"250ml",
    desc:"Targeted anti-dandruff shampoo that soothes the scalp and reduces flaking.",
    benefits:["Fights dandruff & flaking", "Soothes itchy scalp", "Cleanses thoroughly", "Fresh scent"],
    use:{dose:"Massage into wet hair", when:"2-3 times a week", duration:"Until symptoms improve"} },
  { id:62, name:"American Crew Daily Moisturizing Shampoo, 250ml", goal:"shampoo", timing:"anytime",
    rating:4.5, reviews:39, oldPrice:790, price:790, stock:true, tags:[], brand:"American Crew", size:"250ml",
    desc:"Daily hydrating shampoo for men that cleanses without drying out hair or scalp.",
    benefits:["Daily moisture boost", "Gentle, sulfate-conscious", "Gentle scalp cleanse", "Fresh masculine scent"],
    use:{dose:"Small amount, lather & rinse", when:"Every wash", duration:"As needed"} },
  { id:63, name:"Anovia Keratin Smooth Shampoo, 500ml", goal:"shampoo", timing:"anytime",
    rating:4.4, reviews:44, oldPrice:890, price:890, stock:true, tags:[], brand:"Anovia", size:"500ml",
    desc:"Keratin-infused shampoo that smooths frizz and leaves hair silky.",
    benefits:["Smooths frizz", "Adds silky shine", "Keratin-infused formula", "Large value size"],
    use:{dose:"Small amount, lather & rinse", when:"Every wash", duration:"As needed"} },
  { id:64, name:"Alberto Balsam Blends Damage Repair Conditioner, 300ml", goal:"conditioner", timing:"anytime",
    rating:4.3, reviews:41, oldPrice:550, price:450, stock:true, tags:[], brand:"Alberto Balsam", size:"300ml",
    desc:"Lightweight conditioner that detangles and repairs damaged hair after shampooing.",
    benefits:["Detangles easily", "Repairs damage", "Lightweight, non-greasy", "Affordable everyday use"],
    use:{dose:"Apply to mid-lengths & ends", when:"After shampoo", duration:"Every wash"} },
  { id:65, name:"Anovia Healthy Shine Bamboo & Lotus Conditioner, 500ml", goal:"conditioner", timing:"anytime",
    rating:4.4, reviews:36, oldPrice:750, price:690, stock:true, tags:["new"], brand:"Anovia", size:"500ml",
    desc:"Botanical conditioner with bamboo and lotus extracts for added shine and softness.",
    benefits:["Adds natural shine", "Softens hair texture", "Botanical extracts", "Large value size"],
    use:{dose:"Apply to mid-lengths & ends", when:"After shampoo", duration:"Every wash"} },
  { id:66, name:"Anovia Intense Hydration Coconut Water Conditioner, 500ml", goal:"conditioner", timing:"anytime",
    rating:4.5, reviews:52, oldPrice:750, price:690, stock:true, tags:["best"], brand:"Anovia", size:"500ml",
    desc:"Deeply hydrating conditioner infused with coconut water for dry, thirsty hair.",
    benefits:["Deep hydration", "Coconut water infused", "Softens & detangles", "Large value size"],
    use:{dose:"Apply to mid-lengths & ends", when:"After shampoo", duration:"Every wash"} },
  { id:67, name:"A'pieu Raspberry Hair Vinegar, 200ml", goal:"hairoil", timing:"anytime",
    rating:4.5, reviews:29, oldPrice:1690, price:1450, stock:true, tags:["new"], brand:"Apieu", size:"200ml",
    desc:"Rinse-off hair vinegar treatment that clarifies the scalp and adds shine.",
    benefits:["Clarifies scalp buildup", "Adds glossy shine", "Lightweight rinse-off", "Fruity fragrance"],
    use:{dose:"Dilute & rinse after shampoo", when:"1-2 times a week", duration:"Weekly"} },

  /* ---------------- Body Care ---------------- */
  { id:68, name:"Adidas Climacool Shower Gel, 250ml", goal:"bodywash", timing:"anytime",
    rating:4.4, reviews:61, oldPrice:590, price:490, stock:true, tags:["best"], brand:"Adidas", size:"250ml",
    desc:"Refreshing shower gel that cleanses and cools for an energizing wash.",
    benefits:["Refreshing, cooling feel", "Cleanses thoroughly", "Everyday use", "Sporty fragrance"],
    use:{dose:"Small amount, lather & rinse", when:"Daily shower", duration:"Daily"} },
  { id:69, name:"Adidas Dynamic Pulse Men Shower Gel, 250ml", goal:"bodywash", timing:"anytime",
    rating:4.3, reviews:38, oldPrice:950, price:950, stock:true, tags:[], brand:"Adidas", size:"250ml",
    desc:"Energizing men's shower gel with a bold, long-lasting fragrance.",
    benefits:["Long-lasting fragrance", "Cleanses & refreshes", "Everyday use", "Rich lather"],
    use:{dose:"Small amount, lather & rinse", when:"Daily shower", duration:"Daily"} },
  { id:70, name:"APLB Glutathione Niacinamide Body Wash, 300ml", goal:"bodywash", timing:"anytime",
    rating:4.6, reviews:57, oldPrice:2750, price:2150, stock:true, tags:["flash"], brand:"APLB", size:"300ml",
    desc:"Brightening body wash with glutathione and niacinamide for smoother, even-toned skin.",
    benefits:["Brightens skin tone", "Gentle daily cleanse", "Niacinamide-infused", "Non-drying formula"],
    use:{dose:"Small amount, lather & rinse", when:"Daily shower", duration:"Daily"} },
  { id:71, name:"Aveeno Daily Moisturising Body Wash, 300ml", goal:"bodywash", timing:"anytime",
    rating:4.7, reviews:112, oldPrice:1890, price:1690, stock:true, tags:["best"], brand:"Aveeno", size:"300ml",
    desc:"Oat-based moisturizing body wash that cleanses without stripping skin's natural moisture.",
    benefits:["Moisturizes while cleansing", "Soap-free formula", "For sensitive skin", "Soothing oat extract"],
    use:{dose:"Small amount, lather & rinse", when:"Daily shower", duration:"Daily"} },
  { id:72, name:"Almond Milk & Honey Restoring Body Butter, 200ml", goal:"bodylotion", timing:"anytime",
    rating:4.7, reviews:84, oldPrice:1550, price:1550, stock:true, tags:["best"], brand:"The Body Shop", size:"200ml",
    desc:"Rich body butter with almond milk and honey for deep, lasting nourishment.",
    benefits:["Deeply nourishing", "Softens rough skin", "Rich, buttery texture", "Comforting scent"],
    use:{dose:"Apply generously", when:"After shower", duration:"Daily"} },
  { id:73, name:"AmLactin Daily 12% Lactic Acid Moisturizing Lotion, 400g", goal:"bodylotion", timing:"anytime",
    rating:4.6, reviews:49, oldPrice:5090, price:4490, stock:true, tags:["flash"], brand:"AmLactin", size:"400g",
    desc:"Clinical-strength lotion with lactic acid for rough, extra-dry skin.",
    benefits:["Smooths rough patches", "12% lactic acid formula", "Long-lasting hydration", "Fragrance-free option"],
    use:{dose:"Apply generously", when:"Morning & night", duration:"Daily"} },
  { id:74, name:"Aveeno Daily Moisturising Body Lotion — Lavender, 300ml", goal:"bodylotion", timing:"night",
    rating:4.6, reviews:96, oldPrice:1890, price:1490, stock:true, tags:["flash"], brand:"Aveeno", size:"300ml",
    desc:"Calming lavender-scented lotion that moisturizes for 24 hours.",
    benefits:["24-hour moisture", "Calming lavender scent", "Fast-absorbing", "Oat-based formula"],
    use:{dose:"Apply generously", when:"After shower or before bed", duration:"Daily"} },
  { id:75, name:"Aveeno Daily Moisturising Body Cream, 300ml", goal:"bodylotion", timing:"anytime",
    rating:4.7, reviews:88, oldPrice:1890, price:1690, stock:true, tags:["best"], brand:"Aveeno", size:"300ml",
    desc:"Richer cream formula for very dry skin that needs extra nourishment.",
    benefits:["Rich, deep moisture", "For very dry skin", "Fast-absorbing", "Oat-based formula"],
    use:{dose:"Apply generously", when:"After shower", duration:"Daily"} },
  { id:76, name:"Astral Cocoa Butter, 200ml", goal:"bodylotion", timing:"anytime",
    rating:4.4, reviews:33, oldPrice:1290, price:1290, stock:true, tags:[], brand:"Astral", size:"200ml",
    desc:"Classic cocoa butter cream that softens and nourishes dry skin all over.",
    benefits:["Softens dry skin", "Classic cocoa butter", "Versatile everyday use", "Rich texture"],
    use:{dose:"Apply generously", when:"After shower", duration:"Daily"} },
  { id:77, name:"3W Clinic Crystal White Milky Cream, 50g", goal:"bodylotion", timing:"anytime",
    rating:4.3, reviews:28, oldPrice:1290, price:990, stock:true, tags:["new"], brand:"3W Clinic", size:"50g",
    desc:"Brightening milky cream that leaves skin soft and radiant.",
    benefits:["Brightens skin", "Soft, silky finish", "Lightweight cream", "Easy absorption"],
    use:{dose:"Apply to face & body", when:"Morning & night", duration:"Daily"} },
  { id:78, name:"Adidas Victory League Deo Body Spray, 150ml", goal:"deodorant", timing:"morning",
    rating:4.3, reviews:45, oldPrice:450, price:450, stock:true, tags:[], brand:"Adidas", size:"150ml",
    desc:"Long-lasting deodorant body spray that keeps you fresh all day.",
    benefits:["24-hour freshness", "Quick-dry formula", "Everyday use", "Fresh, sporty scent"],
    use:{dose:"Spray from 15cm distance", when:"Morning, after shower", duration:"Daily"} },
  { id:79, name:"Aleda Commando Deodorant Body Spray, 200ml", goal:"deodorant", timing:"morning",
    rating:4.2, reviews:31, oldPrice:550, price:550, stock:true, tags:[], brand:"Aleda", size:"200ml",
    desc:"Affordable everyday deodorant spray with a bold, long-lasting scent.",
    benefits:["Long-lasting scent", "Affordable everyday use", "Quick-dry formula", "Large 200ml size"],
    use:{dose:"Spray from 15cm distance", when:"Morning, after shower", duration:"Daily"} },

  /* ---------------- Makeup ---------------- */
  { id:80, name:"A'pieu Honey & Milk Lip Balm, 17g", goal:"lips", timing:"anytime",
    rating:4.5, reviews:66, oldPrice:950, price:790, stock:true, tags:["best"], brand:"Apieu", size:"17g",
    desc:"Nourishing lip balm with honey and milk extracts for soft, hydrated lips.",
    benefits:["Deeply moisturizes lips", "Honey & milk extracts", "Non-sticky formula", "Everyday use"],
    use:{dose:"Apply as needed", when:"Anytime", duration:"As needed"} },
  { id:81, name:"A'pieu Honey & Milk Lip Oil, 5g", goal:"lips", timing:"anytime",
    rating:4.4, reviews:41, oldPrice:850, price:690, stock:true, tags:["new"], brand:"Apieu", size:"5g",
    desc:"Glossy lip oil that hydrates while giving lips a healthy sheen.",
    benefits:["Glossy, hydrated finish", "Lightweight oil texture", "Honey & milk extracts", "Buildable shine"],
    use:{dose:"Apply as needed", when:"Anytime", duration:"As needed"} },
  { id:82, name:"Abib Protective Lip Balm Stick SPF15, 3.3g", goal:"lips", timing:"morning",
    rating:4.6, reviews:37, oldPrice:790, price:690, stock:true, tags:[], brand:"Abib", size:"3.3g",
    desc:"SPF-protected lip balm that hydrates while shielding lips from sun damage.",
    benefits:["SPF15 lip protection", "Hydrates & softens", "Compact stick format", "Daily use"],
    use:{dose:"Apply as needed", when:"Morning & before sun exposure", duration:"Daily"} },
  { id:83, name:"Beauty Glazed Glow Lip Oil — Sweet", goal:"lips", timing:"anytime",
    rating:4.3, reviews:52, oldPrice:290, price:150, stock:true, tags:["flash"], brand:"Beauty Glazed", size:"1 pc",
    desc:"Glossy tinted lip oil that adds a sheer pop of color with a glassy finish.",
    benefits:["Glassy glow finish", "Sheer buildable tint", "Lightweight, non-sticky", "Affordable everyday glam"],
    use:{dose:"Apply directly to lips", when:"Anytime", duration:"As needed"} },
  { id:84, name:"Beauty Glazed Waterproof Lip Liner — Nude", goal:"lips", timing:"anytime",
    rating:4.2, reviews:34, oldPrice:250, price:130, stock:true, tags:["flash"], brand:"Beauty Glazed", size:"1 pc",
    desc:"Long-wearing, waterproof lip liner that defines and fills for a fuller look.",
    benefits:["Waterproof, long-lasting", "Smooth glide formula", "Defines lip shape", "Affordable everyday glam"],
    use:{dose:"Line & fill lips", when:"Before lipstick", duration:"As needed"} },
  { id:85, name:"Beauty Glazed Waterproof Lip Liner — Coral", goal:"lips", timing:"anytime",
    rating:4.2, reviews:29, oldPrice:250, price:130, stock:true, tags:["flash"], brand:"Beauty Glazed", size:"1 pc",
    desc:"Vibrant coral lip liner with a waterproof, smudge-resistant formula.",
    benefits:["Waterproof, long-lasting", "Vibrant coral shade", "Smooth glide formula", "Affordable everyday glam"],
    use:{dose:"Line & fill lips", when:"Before lipstick", duration:"As needed"} },
  { id:86, name:"AOA Volume Boosting Mascara — Black, 7.8ml", goal:"eyes", timing:"anytime",
    rating:4.4, reviews:59, oldPrice:750, price:750, stock:true, tags:["new"], brand:"AOA Studio", size:"7.8ml",
    desc:"Volumizing mascara that builds bold, defined lashes without clumping.",
    benefits:["Adds visible volume", "Clump-free formula", "Long-wearing black", "Easy to remove"],
    use:{dose:"Apply from root to tip", when:"Anytime", duration:"As needed"} },
  { id:87, name:"Body Collection Concealer, 10ml", goal:"face-makeup", timing:"anytime",
    rating:4.1, reviews:22, oldPrice:250, price:250, stock:true, tags:[], brand:"Body Collection", size:"10ml",
    desc:"Everyday concealer that covers blemishes and evens out skin tone.",
    benefits:["Covers imperfections", "Lightweight, blendable", "Affordable everyday use", "Compact size"],
    use:{dose:"Dab & blend", when:"Anytime", duration:"As needed"} },
  { id:88, name:"Ambre Solaire No Streaks Bronzer BB Body Bronzer, 150ml", goal:"face-makeup", timing:"anytime",
    rating:4.3, reviews:26, oldPrice:730, price:730, stock:true, tags:[], brand:"Garnier", size:"150ml",
    desc:"Streak-free body bronzer that gives a natural sun-kissed glow.",
    benefits:["Natural bronzed glow", "Streak-free application", "Lightweight, non-sticky", "Buildable coverage"],
    use:{dose:"Apply evenly & blend", when:"Anytime", duration:"As needed"} },

  /* ---------------- Mother & Baby ---------------- */
  { id:89, name:"Alberto Balsam Kids Shampoo — Wacky Watermelon 2in1, 250ml", goal:"babycare", timing:"anytime",
    rating:4.5, reviews:48, oldPrice:1050, price:990, stock:true, tags:["new"], brand:"Alberto Balsam", size:"250ml",
    desc:"Tear-free 2-in-1 kids' shampoo with a fun watermelon scent.",
    benefits:["Tear-free formula", "2-in-1 shampoo & conditioner", "Fun fruity scent", "Gentle on scalp"],
    use:{dose:"Small amount, lather & rinse", when:"Bath time", duration:"As needed"} },
  { id:90, name:"Asda Little Angels Baby Lotion, 500ml", goal:"babycare", timing:"anytime",
    rating:4.6, reviews:61, oldPrice:1150, price:1050, stock:true, tags:["best"], brand:"Asda", size:"500ml",
    desc:"Gentle, hypoallergenic baby lotion that keeps delicate skin soft and moisturized.",
    benefits:["Hypoallergenic formula", "24-hour moisture", "Gentle, mild fragrance", "Large value size"],
    use:{dose:"Apply after bath", when:"Daily", duration:"Daily"} },
  { id:91, name:"Asda Little Angels Head to Toe Wash, 500ml", goal:"babycare", timing:"anytime",
    rating:4.5, reviews:53, oldPrice:1590, price:1290, stock:true, tags:["flash"], brand:"Asda", size:"500ml",
    desc:"Gentle no-tears wash for baby's hair and body in one bottle.",
    benefits:["No-tears formula", "Cleanses hair & body", "Dermatologically tested", "Mild, gentle fragrance"],
    use:{dose:"Small amount, lather & rinse", when:"Bath time", duration:"Daily"} },
  { id:92, name:"Asda Little Angels Protective Nappy Cream, 200g", goal:"babycare", timing:"anytime",
    rating:4.6, reviews:44, oldPrice:650, price:590, stock:true, tags:[], brand:"Asda", size:"200g",
    desc:"Protective barrier cream that soothes and guards against nappy rash.",
    benefits:["Soothes nappy rash", "Protective barrier", "Gentle on delicate skin", "Dermatologically tested"],
    use:{dose:"Apply thin layer at each change", when:"Every nappy change", duration:"As needed"} },
  { id:93, name:"Aveeno Baby Calming Comfort Bedtime Bath & Wash, 300ml", goal:"babycare", timing:"night",
    rating:4.7, reviews:79, oldPrice:1990, price:1690, stock:true, tags:["best"], brand:"Aveeno", size:"300ml",
    desc:"Calming lavender & vanilla bedtime wash that helps soothe baby before sleep.",
    benefits:["Calming lavender scent", "Gentle, tear-free", "Oat-based formula", "Part of bedtime routine"],
    use:{dose:"Small amount, lather & rinse", when:"Bedtime bath", duration:"Nightly"} },
  { id:94, name:"Aveeno Baby Daily Care Gentle Bath & Wash, 400ml", goal:"babycare", timing:"anytime",
    rating:4.6, reviews:67, oldPrice:1990, price:1790, stock:true, tags:["flash"], brand:"Aveeno", size:"400ml",
    desc:"Everyday gentle wash formulated for baby's sensitive skin.",
    benefits:["Gentle daily cleanse", "Tear-free formula", "Oat-based formula", "Dermatologically tested"],
    use:{dose:"Small amount, lather & rinse", when:"Bath time", duration:"Daily"} },
  { id:95, name:"Aveeno Baby Daily Care 2-In-1 Shampoo & Conditioner, 300ml", goal:"babycare", timing:"anytime",
    rating:4.6, reviews:58, oldPrice:1490, price:1190, stock:true, tags:["flash"], brand:"Aveeno", size:"300ml",
    desc:"Gentle 2-in-1 formula that cleanses and conditions baby's hair in one step.",
    benefits:["2-in-1 convenience", "Tear-free formula", "Detangles gently", "Oat-based formula"],
    use:{dose:"Small amount, lather & rinse", when:"Bath time", duration:"As needed"} },
  { id:96, name:"Always Ultra Long Sanitary Pads with Wings, 12 Pack", goal:"maternity", timing:"anytime",
    rating:4.5, reviews:73, oldPrice:790, price:450, stock:true, tags:["flash"], brand:"Always", size:"12 pads",
    desc:"Reliable long sanitary pads with wings for secure, comfortable protection.",
    benefits:["Secure wing design", "Long-length coverage", "Absorbent core", "Comfortable all-day wear"],
    use:{dose:"Change every 4-6 hours", when:"As needed", duration:"As needed"} },
  { id:97, name:"Always Ultra Night Sanitary Pads, 10 Pack", goal:"maternity", timing:"anytime",
    rating:4.6, reviews:64, oldPrice:790, price:450, stock:true, tags:["flash"], brand:"Always", size:"10 pads",
    desc:"Extra-coverage night pads designed for secure overnight protection.",
    benefits:["Extended night coverage", "Leak-guard sides", "Absorbent core", "Comfortable overnight wear"],
    use:{dose:"Use overnight", when:"Nightly as needed", duration:"As needed"} },

  /* ---------------- Men's Care ---------------- */
  { id:98, name:"Bulldog Original Beard Oil, 30ml", goal:"beardcare", timing:"anytime",
    rating:4.6, reviews:58, oldPrice:1190, price:850, stock:true, tags:["flash"], brand:"Bulldog", size:"30ml",
    desc:"Lightweight beard oil that softens and conditions facial hair with natural oils.",
    benefits:["Softens beard hair", "Conditions skin beneath", "Natural oil blend", "Non-greasy finish"],
    use:{dose:"2-3 drops, massage in", when:"Morning & night", duration:"Daily"} },
  { id:99, name:"Dr. Rashel Beard Oil with Argan Oil & Vitamin E, 30ml", goal:"beardcare", timing:"anytime",
    rating:4.4, reviews:37, oldPrice:690, price:690, stock:true, tags:["new"], brand:"Dr. Rashel", size:"30ml",
    desc:"Nourishing beard oil enriched with argan oil and vitamin E for a fuller, healthier beard.",
    benefits:["Nourishes with argan oil", "Vitamin E enriched", "Reduces beard itch", "Promotes healthy growth"],
    use:{dose:"2-3 drops, massage in", when:"Morning & night", duration:"Daily"} },
  { id:100, name:"Gillette Fusion5 Men's Razor", goal:"shaving", timing:"morning",
    rating:4.7, reviews:143, oldPrice:1450, price:1190, stock:true, tags:["best"], brand:"Gillette", size:"1 razor",
    desc:"5-blade razor system engineered for a close, comfortable shave.",
    benefits:["5-blade close shave", "Lubrication strip", "Precision trimmer edge", "Ergonomic handle"],
    use:{dose:"Use with shaving gel/foam", when:"Morning", duration:"Blades last ~2-4 weeks"} },
  { id:101, name:"Gillette Fusion5 Action Shaving Gel with Almond Oil, 200ml", goal:"shaving", timing:"morning",
    rating:4.5, reviews:62, oldPrice:850, price:850, stock:true, tags:[], brand:"Gillette", size:"200ml",
    desc:"Rich shaving gel with almond oil for a smooth, comfortable glide.",
    benefits:["Smooth razor glide", "Almond oil moisture", "Rich, cushioning lather", "Reduces irritation"],
    use:{dose:"Lather onto damp skin", when:"Before shaving", duration:"As needed"} },
  { id:102, name:"Gillette Fusion ProGlide Active Sport Shaving Foam, 250ml", goal:"shaving", timing:"morning",
    rating:4.5, reviews:41, oldPrice:990, price:990, stock:true, tags:[], brand:"Gillette", size:"250ml",
    desc:"Sport-formula shaving foam for a fresh, comfortable shave before an active day.",
    benefits:["Rich, protective lather", "Fresh, energizing scent", "Reduces razor burn", "Everyday use"],
    use:{dose:"Lather onto damp skin", when:"Before shaving", duration:"As needed"} },
  { id:103, name:"BIC Triple Blade Disposable Razor, Pack of 4", goal:"shaving", timing:"morning",
    rating:4.3, reviews:35, oldPrice:650, price:590, stock:true, tags:["flash"], brand:"BIC", size:"4 razors",
    desc:"Convenient disposable triple-blade razors for a quick, close shave.",
    benefits:["Triple-blade design", "Convenient disposable", "Lubricating strip", "Value 4-pack"],
    use:{dose:"Use with shaving gel/foam", when:"Anytime", duration:"Single use per razor"} },
  { id:104, name:"Garnier Men Turbo Bright Shaving & Brightening Foam, 100ml", goal:"shaving", timing:"morning",
    rating:4.2, reviews:28, oldPrice:790, price:490, stock:true, tags:["flash"], brand:"Garnier", size:"100ml",
    desc:"2-in-1 shaving foam that cleanses and brightens skin while you shave.",
    benefits:["2-in-1 shave & brighten", "Reduces dullness", "Rich lather", "Fresh scent"],
    use:{dose:"Lather onto damp skin", when:"Before shaving", duration:"As needed"} },
  { id:105, name:"Aveeno Positively Smooth Shave Gel, 198g", goal:"shaving", timing:"anytime",
    rating:4.6, reviews:39, oldPrice:1790, price:1590, stock:true, tags:["best"], brand:"Aveeno", size:"198g",
    desc:"Soap-free shave gel with soy extract for a smooth, irritation-free shave.",
    benefits:["Reduces razor irritation", "Soy extract formula", "Smooth, close shave", "Soap-free formula"],
    use:{dose:"Apply to damp skin", when:"Before shaving", duration:"As needed"} },

  /* ---------------- Foods ---------------- */
  { id:106, name:"Al Shifa Natural Honey, 500g", goal:"honey", timing:"anytime",
    rating:4.7, reviews:118, oldPrice:750, price:750, stock:true, tags:["best"], brand:"Al Shifa", size:"500g",
    desc:"Natural honey with no added sugar, sourced for everyday nutrition.",
    benefits:["100% natural honey", "No added sugar", "Everyday nutrition", "Large value size"],
    use:{dose:"1-2 tsp", when:"Anytime", duration:"Daily"} },
  { id:107, name:"Asda Classic Runny Honey, 720g", goal:"honey", timing:"anytime",
    rating:4.5, reviews:52, oldPrice:2190, price:1950, stock:true, tags:["flash"], brand:"Asda", size:"720g",
    desc:"Smooth, runny honey perfect for tea, toast or everyday cooking.",
    benefits:["Smooth runny texture", "Versatile everyday use", "Large 720g jar", "Naturally sweet"],
    use:{dose:"As desired", when:"Anytime", duration:"As needed"} },
  { id:108, name:"Asda Pure Clear Honey, 908g", goal:"honey", timing:"anytime",
    rating:4.5, reviews:47, oldPrice:1850, price:1850, stock:true, tags:[], brand:"Asda", size:"908g"    ,
    desc:"Large jar of pure clear honey, great value for regular households.",
    benefits:["Pure, clear honey", "Great value large size", "Versatile everyday use", "Naturally sweet"],
    use:{dose:"As desired", when:"Anytime", duration:"As needed"} },
  { id:109, name:"Asda Runny Honey, 340g", goal:"honey", timing:"anytime",
    rating:4.4, reviews:31, oldPrice:750, price:750, stock:true, tags:[], brand:"Asda", size:"340g",
    desc:"Convenient smaller jar of smooth runny honey for everyday use.",
    benefits:["Smooth runny texture", "Convenient jar size", "Versatile everyday use", "Naturally sweet"],
    use:{dose:"As desired", when:"Anytime", duration:"As needed"} },
  { id:110, name:"Davidoff Café Espresso 57 Intense Instant Coffee, 100g", goal:"drygoods", timing:"morning",
    rating:4.6, reviews:56, oldPrice:1190, price:890, stock:true, tags:["flash"], brand:"Davidoff", size:"100g",
    desc:"Intense instant espresso coffee jar for a rich, bold cup at home.",
    benefits:["Rich, intense flavor", "Instant convenience", "Premium coffee jar", "Bold espresso profile"],
    use:{dose:"1-2 tsp per cup", when:"Morning or anytime", duration:"As needed"} },
  { id:111, name:"Davidoff Fine Aroma Instant Coffee, 100g", goal:"drygoods", timing:"morning",
    rating:4.5, reviews:38, oldPrice:1190, price:890, stock:true, tags:["flash"], brand:"Davidoff", size:"100g",
    desc:"Smooth, aromatic instant coffee for a balanced everyday brew.",
    benefits:["Smooth, balanced flavor", "Instant convenience", "Aromatic blend", "Premium coffee jar"],
    use:{dose:"1-2 tsp per cup", when:"Morning or anytime", duration:"As needed"} },
  { id:112, name:"ASDA Green Tea, 50 Tea Bags, 100g", goal:"drygoods", timing:"anytime",
    rating:4.3, reviews:24, oldPrice:650, price:650, stock:true, tags:[], brand:"Asda", size:"50 bags",
    desc:"Everyday green tea bags for a light, refreshing cup any time of day.",
    benefits:["Light, refreshing taste", "50 tea bags per box", "Everyday value pack", "Rich in antioxidants"],
    use:{dose:"1 bag per cup", when:"Anytime", duration:"As needed"} },
  { id:113, name:"Celebrations Chocolate Pouch, 370g", goal:"drygoods", timing:"anytime",
    rating:4.6, reviews:41, oldPrice:1150, price:1150, stock:true, tags:["new"], brand:"Mars", size:"370g",
    desc:"Assorted mini chocolates, perfect for sharing or gifting.",
    benefits:["Assorted chocolate mix", "Great for sharing", "Gift-friendly pouch", "Popular imported brand"],
    use:{dose:"As desired", when:"Anytime", duration:"As needed"} },

];